### ISSUE TITLE
Running as tampermonkey userscript breaks certain features

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#10]
I noticed "Fixed pointer breaking if you click" was not working when I ran the script through tampermonkey.

Now I'm concerned what other features might not be working.

**Comment by ensingm2** [comment]
Fixed in https://github.com/ensingm2/SteamMonsterGameScript/commit/08db9f7cd469812af9baf5c0caf88e5c920f81c5

It was just due to the fact that tampermonkey loaded my function overwrite code before loading the actual game. This led to the base game overwriting me instead. There was already a fix in place for the other functions, this was the only issue affected by that.
