### ISSUE TITLE
Inefficient gold farming because of different scripts?

### ISSUE THREAD

**Issue by garfieldbanks** [ensingm2/SteamMonsterGameScript#100]
Is it true that the use of different scripts is causing inefficient gold farming? If so, can we merge the parts of the code dealing with that with the other scripts?

https://steamcommunity.com/groups/MSG2015/discussions/0/598198356177708591/

**Comment by ensingm2** [comment]
As of https://github.com/ensingm2/SteamMonsterGameScript/commit/4c9c0f6c51d49db0c16968f40e66a65cf94e187b, This script takes an estimate of time until death on the target boss, and only uses Raining Gold if they are be expected to be alive for the full duration.

We nuke bosses after level 1000, and use raining gold on every 20th boss(levelNum % 200 === 0) (As long as they meet the above condition). This was in line with what used to be SteamDB's settings, but last I checked both them and wchill were tweaking their nuke settings. Until that tweaking settles down and is figured out, it's tough to make them the same.

That said, post level 1000 I personally think it's actually a beneficial thing that some scripts are nuking while others are gold farming, as long as they all follow the 'only use raining gold if the boss is going to stay alive' logic. Otherwise, all scripts would raining gold the same boss and they would likely get stuck on that level for long after they run out of raining gold items.
.
