### ISSUE TITLE
Decreased Cooldowns

### ISSUE THREAD

**Issue by cdmichaelb** [ensingm2/SteamMonsterGameScript#159]
I almost never (well actually never) see it used. Seems like even if you can't find a good way to maximize it's benefit maybe cast it before napalm any time it's up? (I think napalm is the best ability)

**Comment by ensingm2** [comment]
Current logic for using Decrease Cooldowns is to use just before Morale Booster and/or Good Luck charm (they're used as a combo if possible) if a Decrease Cooldowns is not already active. This is in an attempt to cast semi-selfishly and attempt to get at least 2 reductions out of the use (Pretty much all other abilities are not combo'd so you'd only get 1 reduced CD there).

I'll probably add an alternate condition that uses it during of a boss fight if one isn't already active in order to help the lane. That should increase the number of uses a lot (since you're in a boss fight every 10 levels and the CD is an hour).

**Comment by sinnoaria** [comment]
A thought is to have a setting for using it before the Metal Detector instead.

**Comment by ensingm2** [comment]
Why specifically metal detector? metal detector gets used towards the end of boss fights, so it's likely that less abilities are being used at that time and thus you get less benefit.

**Comment by sinnoaria** [comment]
For those of us that would rather maximize the benefit of more gold. Especially when the bosses are dying in like less than 5 seconds even without nukes.

**Comment by ensingm2** [comment]
Right, but is there a reason to wait specifically for metal detector rather than using it at the start of the boss fight like I proposed? More abilities are used then so It'd get more use, and if the bosses are dying immediately anyway it'll still be active for metal.

**Comment by ensingm2** [comment]
Fixed with https://github.com/ensingm2/SteamMonsterGameScript/commit/efb33e10fce78afe2b4c92e22d02e121684207fe

You now auto-cast Decrease Cooldowns at the start of boss rounds
