### ISSUE TITLE
Crit vs Elemental

### ISSUE THREAD

**Issue by Ashnal** [ensingm2/SteamMonsterGameScript#160]
As the game goes on, it becomes obvious that Crit and Crit damage stacking far out paces elemental stacking. If you're in one of the good rooms, you can easily have >50% crit within the first hour, and 100% easily later on.

Since Crit and elemental don't stack, I suggest ignoring elemental upgrades completely if you have more than 25% crit (including unused crit abilities) to optimize money spending.

**Comment by SM411** [comment]
On the same subject. If crit-chance is lower then 100%, spam Crit consumable.

**Comment by ensingm2** [comment]
@ashnal: player crit chance is already taken into account when automatically deciding what upgrade yields the best DPS. I will however add a check that takes unused Crit items into account, that should resolve the issue of your elemental DPS prioritizing because you don't _technically_ have high enough crit chance (yet) since you haven't applied your crit items

@SM411 Since crit also deploys Good Luck Charm, I use it on the same logic that ability is used (but prioritized over the ability). This is to maximize the active part of the effect. I will be adding a 'spam all permanent stat boosters' setting however that will do this.

**Comment by InfamousChloe** [comment]
The upgrade is crit DAMAGE, the Crit item is the only thing that adds crit chance. It would be way better to spam Crit items ASAP unless you're at 100% crit chance, which is cap.

**Comment by ensingm2** [comment]
What? I think you misunderstood what I was saying. We're talking about upgrading elements vs damage, not specifically lucky shot.

**Comment by InfamousChloe** [comment]
My mistake, didn't realize you meant crit chance was taken into account for OTHER upgrades.

**Comment by ensingm2** [comment]
yup, no worries.
