### ISSUE TITLE
Wormhole + Raining Gold

### ISSUE THREAD

**Issue by cdmichaelb** [ensingm2/SteamMonsterGameScript#172]
The wormhole reverts the gold you earned from Raining Gold. Not good to use on same level.

**Comment by ensingm2** [comment]
Are you sure?

**Comment by cdmichaelb** [comment]
Not 100% sure as the tooltip says "skipped levels give no gold" but it appears to revert each time.

**Comment by ensingm2** [comment]
Hmm, ok. I'll look into it.

**Comment by zinefer** [comment]
I bet this refers to the end gold of the skipped levels after the WH, not the level the wormhole is used on.

**Comment by ensingm2** [comment]
@zinefer Looking back, I'm almost positive you're right.

The tooltip says that **_after the current level**_ it skips the _next_ level, and no gold is awarded on skipped levels.

This implies that the _next_ level does not give any gold. Therefore, using raining gold is fine, since you're still on your 'current level'.

Closing this issue, feel free to reopen or continue commenting if I'm mistaken.
