### ISSUE TITLE
Medic never auto deploy for those with high health

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#27]
I suggest we make medics deploy as soon as available in order to focus on healing the team rather than healing ourselves.

For those of us leveling Energy Shields medics are unlikely to ever deploy as health never drops below 30%.

I know I can manually change useMedicsAtPercent to 100, but I would be required to do so after each update. It makes more sense to have deployment conditions which are ideal for everyone.

**Comment by ensingm2** [comment]
I'll look into adding another option when overall lane health is below a threshold

**Comment by DannyDaemonic** [comment]
If you look in the full version of the code, you can change the variable **useMedicsAtPercent**. It is set to 30 (percent) by default. To make it act like you want, just set it to 100.

**Comment by ensingm2** [comment]
Updated to also trigger medic use selflessly to help the lane, if useMedicsAtLanePercentAliveReq (40% default) of the lane is alive and average lane health is below useMedicsAtLanePercent (50% default)

**Comment by DannyDaemonic** [comment]
The percent alive will vary from game to game (room to room) depending on how many active players there are, there's no point in counting idle players towards the LanePercent since they will be dead for 5 minutes at a time, but I can't figure out how to see which players are active. Some sites out there, such as [this one](https://lab.xpaw.me/towerattack.php), seem to know the number of "active" players.

**Comment by ensingm2** [comment]
Right, which is why the required percent of alive players is relatively low. I'd agree that only counting active players would be nice.
