### ISSUE TITLE
bestDamageUpgrade ignores elemental multiplier for Damage upgrades

### ISSUE THREAD

**Issue by dralex75** [ensingm2/SteamMonsterGameScript#35]
The dpg calcs for elemental upgrades take into account the current dpc base:

var dpc = scene.m_rgPlayerTechTree.damage_per_click;

The calculations for click damage upgrades and auto-damage upgrades ignore the elemental multipliers.

dpg = (scene.m_rgTuningData.player.damage_per_click \* data.multiplier \* 10 )/ cost;

for railgun this ends up as:

dpg = (10 \* 100 )/ cost;

End result is you will pick an elemental upgrade for  6 -> 7 costing 160m over a railgun upgrade for 54m

**Comment by dralex75** [comment]
simple code for elemental multiplier calc:

```
    var maxLevels = gElementalUpgrades.reduce(function(max, id) {
        if(max < getUpgrade(id).level) {
            return getUpgrade(id).level;
        }
        return max;
    }, 1);
var elementalMultiplier = (maxLevels * 1.5) + 1;
```

**Comment by dralex75** [comment]
er, initial value should be 0

var maxLevels = gElementalUpgrades.reduce(function(max, id) {
        if(max < getUpgrade(id).level) {
            return getUpgrade(id).level;
        }
        return max;
    }, 0);
var elementalMultiplier = (maxLevels \* 1.5) + 1;

**Comment by ensingm2** [comment]
I have barely touched the autoBuyer code so bear with me if I mess something up.

So that's why for the elementals we have the elementalCoefficient, which serves to estimate the fact that you aren't always recieving that bonus damage.

So say we have elemental upgrade 6->7 (assuming you're leveling 2 equally so total level 12) vs railgun (you didn't give a level so we'll just say level n->n+1) as you said.

dpc = some constant

elementalCost = data.cost \* Math.pow(data.cost_exponential_base, elementalLevels) = 50 \* 2.2^12 = 642750
elementalDPG = (elementalCoefficient \* dpc) \* data.multiplier / elementalCost 
elementalDPG = (0.35_dpc)_1.5 / 642750 = (7/8570000)*dpc = about 8.168e-7 \* dpc
railgunCost = data.cost \* Math.pow(data.cost_exponential_base, elementalLevels) = 100000 \* 2.2^n
railgunDPG = dpc \* 100 / railgunCost = dpc / (1000 \* 2.2^n)

elementalDPG vs railgunDPG
(7/8570000) vs (1/(1000 \* 2.2^n))

Your tipping point is railgun level 9.02, so railgun levels 0-9 will favor the railgun upgrade. Anything above that will favor the elemental upgrade This seems about right to  me. Is this not the case in practice?

**Comment by dralex75** [comment]
My point was that elemental multiplier isn't referenced in the dpg calculation for railgun (and all other damage dealers) at all and it should be.

dpg = (scene.m_rgTuningData.player.damage_per_click \* data.multiplier)/ cost;

For railgun this is always:

dpg = (10 \* 100 ) / 1000 \* 2.2^n

No matter if you have 20/20/20/20 elemental or 0/0/0/0.

**Comment by ensingm2** [comment]
Can you confirm whether or not this is fixed as of https://github.com/ensingm2/SteamMonsterGameScript/commit/84cc7256ab4e7df26fbde66ab7d3863f24eb4e2a ?

**Comment by dralex75** [comment]
looks like it is fixed in https://github.com/ensingm2/SteamMonsterGameScript/commit/5fc8afd8eb4f429500d1ad18c7837e1cc5f10cca

thanks.

**Comment by ensingm2** [comment]
Awesome
