### ISSUE TITLE
Heavily favoring HP Upgrades?

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#79]
[The auto-buyer for me has frozen up because it's currently trying to buy a personal training upgrade costing 249m while I'm still at level 56 with only 35077k.](http://www.reddit.com/r/SteamMonsterGame/comments/39lv9t/customizable_js_autoclicker_targetlanechanger_and/cs6wkvz?context=3)

Seems like there may be some issue I can't find @meishuu, can you take a look?

**Comment by meishuu** [comment]
This kind of makes sense.

I don't think it's "heavily favoring" armor. It's just trying to pick the item with the most health-per-gold, and if Personal Training is unlocked, that may very well be it.

But unlike with click damage, this really shouldn't be something we want to wait for, so we perhaps want to modify the algorithm to pick something we can obtain within a realistic time?

It would be nice if we can calculate our average income over time for this, otherwise we'll just have to ignore armor upgrades that we can't afford yet.
