### ISSUE TITLE
Medics for allies does not seem to be working

### ISSUE THREAD

**Issue by cdmichaelb** [ensingm2/SteamMonsterGameScript#85]
The default options I've never seen it used, I'm not really sure how I would edit it to make it use it more liberally. I stack high HP because why not? So I literally never need to self Medics. My solution for now has been to use it at 100% of my HP, but I'd like for it to help others out more.

**Comment by ensingm2** [comment]
var useMedicsAtLanePercent = x; (default is 40, does not take dead teammates into avg since they aren't healed)

change it to what you will. I'll probably increase the threshold to 60-75 as I haven't seen it trigger almost ever myself, but I'm in the middle of a pretty big branch out so it'll be a little bit.

**Comment by ensingm2** [comment]
Also 
var useMedicsAtLanePercentAliveReq = x; (default is 40)
Requires x% of the lane to be alive before using medic selflessly in order to maximize team heal.

I'll probably drop this too since a lot of afks stay dead.

**Comment by ensingm2** [comment]
Should work and actually get triggered now.
